CREATE TABLE [invnt].[Products] (
    [ProductId]        BIGINT           IDENTITY (1, 1) NOT NULL,
    [ProductKey]       UNIQUEIDENTIFIER NULL,
    [ProdCtgId]        BIGINT           NOT NULL,
    [ProdSubCtgId]     BIGINT           NULL,
    [UnitId]           BIGINT           NOT NULL,
    [FinalPrice]       DECIMAL (10, 2)  NOT NULL,
    [PreviousPrice]    DECIMAL (10, 2)  NULL,
    [CurrencyId]       BIGINT           NOT NULL,
    [TagWord]          NVARCHAR (250)   NULL,
    [ProdName]         NVARCHAR (150)   NOT NULL,
    [ManufacturarName] NVARCHAR (150)   NULL,
    [SerialNmbrOrUPC]  NVARCHAR (150)   NULL,
    [Sku]              NVARCHAR (150)   NULL,
    [OpeningQnty]      INT              NOT NULL,
    [AlertQnty]        INT              NULL,
    [BuyingPrice]      DECIMAL (10, 2)  NOT NULL,
    [SellingPrice]     DECIMAL (10, 2)  NOT NULL,
    [VatPercent]       DECIMAL (10, 2)  NULL,
    [VatAmount]        DECIMAL (10, 2)  NULL,
    [DiscountPercentg] DECIMAL (10, 2)  NULL,
    [DiscountAmount]   DECIMAL (10, 2)  NULL,
    [BarCode]          NVARCHAR (250)   NULL,
    [SupplirLinkId]    INT              NULL,
    [ImportedForm]     NVARCHAR (150)   NULL,
    [ImportStatusId]   INT              NULL,
    [GivenEntryDate]   DATETIME         NULL,
    [WarrentYear]      INT              NULL,
    [WarrentyPolicy]   NVARCHAR (MAX)   NULL,
    [ColorId]          INT              NULL,
    [SizeId]           INT              NULL,
    [ShippingById]     INT              NULL,
    [ShippingDays]     INT              NULL,
    [ShippingDetails]  NVARCHAR (MAX)   NULL,
    [OriginCountryId]  INT              NULL,
    [Rating]           INT              NULL,
    [ProdStatusId]     INT              NULL,
    [Remarks]          NVARCHAR (MAX)   NULL,
    [ProdDescription]  NVARCHAR (MAX)   NULL,
    [ReleaseDate]      DATETIME         NULL,
    [BranchId]         BIGINT           NOT NULL,
    [StockQuantity]    INT              NOT NULL,
    [ItemWeight]       DECIMAL (18, 2)  NULL,
    [WarehouseId]      BIGINT           NULL,
    [RackNumber]       NVARCHAR (50)    NULL,
    [BatchNumber]      NVARCHAR (50)    NULL,
    [PolicyId]         BIGINT           NULL,
    [EntryDateTime]    DATETIME         NULL,
    [EntryBy]          BIGINT           NULL,
    [LastModifyDate]   DATETIME         NULL,
    [LastModifyBy]     BIGINT           NULL,
    [DeletedDate]      DATETIME         NULL,
    [DeletedBy]        BIGINT           NULL,
    [ProdStatus]       VARCHAR (10)     NULL,
    CONSTRAINT [PK_ProductId] PRIMARY KEY CLUSTERED ([ProductId] ASC)
);

