CREATE TABLE [stt].[Suppliers] (
    [SupplierId]      BIGINT           IDENTITY (1, 1) NOT NULL,
    [SupplierKey]     UNIQUEIDENTIFIER NOT NULL,
    [BranchId]        BIGINT           NULL,
    [SupplrName]      NVARCHAR (100)   NOT NULL,
    [MobileNo]        NVARCHAR (100)   NOT NULL,
    [Email]           NVARCHAR (100)   NOT NULL,
    [SuppOrgnznName]  NVARCHAR (200)   NOT NULL,
    [CountryId]       BIGINT           NOT NULL,
    [StateName]       NVARCHAR (100)   NOT NULL,
    [BusinessTypeId]  BIGINT           NOT NULL,
    [SupplrAddrssOne] NVARCHAR (MAX)   NULL,
    [SupplrAddrssTwo] NVARCHAR (MAX)   NULL,
    [DeliveryOffDay]  NVARCHAR (80)    NULL,
    [SupplrImgLink]   NVARCHAR (180)   NULL,
    [EntryDateTime]   DATETIME         NULL,
    [EntryBy]         BIGINT           NULL,
    [LastModifyDate]  DATETIME         NULL,
    [LastModifyBy]    BIGINT           NULL,
    [DeletedDate]     DATETIME         NULL,
    [DeletedBy]       BIGINT           NULL,
    [Status]          VARCHAR (10)     NULL,
    CONSTRAINT [PK_SupplierInfo] PRIMARY KEY CLUSTERED ([SupplierId] ASC)
);

