CREATE TABLE [dbo].[Title] (
    [WORKER_REF_ID] INT       NULL,
    [WORKER_TITLE]  CHAR (25) NULL,
    [AFFECTED_FROM] DATETIME  NULL,
    FOREIGN KEY ([WORKER_REF_ID]) REFERENCES [dbo].[Worker] ([WORKER_ID]) ON DELETE CASCADE
);

