// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorAppServerAppTest.Models;

[Keyless]
public partial class Bonus
{
    public int? WORKER_REF_ID { get; set; }

    public int? BONUS_AMOUNT { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BONUS_DATE { get; set; }

    public int? WORKER_ID { get; set; }

    [ForeignKey("WORKER_ID")]
    public virtual Worker WORKER { get; set; }
}