// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorAppServerAppTest.Models;

[Keyless]
public partial class loan_data
{
    [StringLength(50)]
    [Unicode(false)]
    public string particular { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ld_no { get; set; }

    [Column(TypeName = "date")]
    public DateTime? loan_date { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? loan_amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? interest { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? total_amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? adjusted_1 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? adjusted_2 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? adjusted_3 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? adjusted_4 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? adjusted_5 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? adjusted_6 { get; set; }
}