// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorAppServerAppTest.Models
{
    public partial class MostSuccessNdFaildCampaingResult
    {
        public string status { get; set; }
        public string CusName { get; set; }
        public string cmpnName { get; set; }
        public int? total { get; set; }
    }
}
