// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorAppServerAppTest.Models;

public partial class Order
{
    [Key]//primary key
    public long OrderId { get; set; }  //bigint

    public Guid OrderKey { get; set; }

    [Required]
    [StringLength(100)]
    public string ProductName { get; set; }//string datatype //nvarchar

    public long? CategoryId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OrderDate { get; set; }
    public bool? IsProductRecieve { get; set; }
    public DateTime EntryDateTime { get; set; }
    public long EntryBy { get; set; }
    public string Status { get; set; }
}