// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorAppServerAppTest.Models;

[Keyless]
public partial class customers
{
    public int? id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string first_name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string last_name { get; set; }
}