// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorAppServerAppTest.Models
{
    public partial class Party_seats_won_functionResult
    {
        public string party_seats_won { get; set; }
    }
}
