// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlazorAppServerAppTest.Models;

public partial class practiceDbContext : DbContext
{
    public practiceDbContext(DbContextOptions<practiceDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bonus> Bonus { get; set; }

    public virtual DbSet<Category> Category { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<Title> Title { get; set; }

    public virtual DbSet<Worker> Worker { get; set; }

    public virtual DbSet<WorkerClone> WorkerClone { get; set; }

    public virtual DbSet<campaigns> campaigns { get; set; }

    public virtual DbSet<candidates> candidates { get; set; }

    public virtual DbSet<candidates_tab> candidates_tab { get; set; }

    public virtual DbSet<customers> customers { get; set; }

    public virtual DbSet<events> events { get; set; }

    public virtual DbSet<loan_data> loan_data { get; set; }

    public virtual DbSet<loan_data2> loan_data2 { get; set; }

    public virtual DbSet<results> results { get; set; }

    public virtual DbSet<results_tab> results_tab { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bonus>(entity =>
        {
            entity.HasOne(d => d.WORKER).WithMany()
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Bonus__WORKER_ID__48CFD27E");
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Products__3214EC07A47DCBE6");
        });

        modelBuilder.Entity<Title>(entity =>
        {
            entity.Property(e => e.WORKER_TITLE).IsFixedLength();

            entity.HasOne(d => d.WORKER_REF).WithMany()
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Title__WORKER_RE__5BE2A6F2");
        });

        modelBuilder.Entity<Worker>(entity =>
        {
            entity.HasKey(e => e.WORKER_ID).HasName("PK__Worker__03DCC97FF53A71B4");

            entity.Property(e => e.WORKER_ID).ValueGeneratedNever();
            entity.Property(e => e.DEPARTMENT).IsFixedLength();
        });

        modelBuilder.Entity<WorkerClone>(entity =>
        {
            entity.Property(e => e.DEPARTMENT).IsFixedLength();
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}