// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using BlazorAppServerAppTest.Models;

namespace BlazorAppServerAppTest.Models
{
    public partial class practiceDbContext
    {

        [DbFunction("MostSuccessNdFaildCampaing", "dbo")]
        public IQueryable<MostSuccessNdFaildCampaingResult> MostSuccessNdFaildCampaing()
        {
            return FromExpression(() => MostSuccessNdFaildCampaing());
        }

        [DbFunction("Party_seats_won_function", "dbo")]
        public IQueryable<Party_seats_won_functionResult> Party_seats_won_function()
        {
            return FromExpression(() => Party_seats_won_function());
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MostSuccessNdFaildCampaingResult>().HasNoKey();
            modelBuilder.Entity<Party_seats_won_functionResult>().HasNoKey();
        }
    }
}
